apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/victoralbucorde/teste-github-actions.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true